## 텐서 기본 정의, 연산, Numpy변환

In [ ]:
%matplotlib inline


## pytorch 튜토리얼 정리 

목표  
• 높은 수준에서 PyTorch의 Tensor library와 신경망(Neural Network)를 이해  
• 이미지를 분류하는 작은 신경망을 학습  


PyTorch란?  
Python 기반의 과학 연산 패키지  
• NumPy를 대체, GPU를 이용한 연산  
• 최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

## Tensor

In [1]:
from __future__ import print_function # 파이썬2,3 어떤 버전을 돌리던 모두 파이썬 문법으로 출력 가능
import torch

초기화 되지 않은 5x3 행렬 생성



In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[6.0225e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 2.2003e-36]])


무작위로 초기화된 행렬 생성



In [3]:
x = torch.rand(5, 3) # 0~1 사이의 숫자
print(x)

tensor([[0.2149, 0.3929, 0.1520],
        [0.8440, 0.5025, 0.4160],
        [0.3561, 0.8950, 0.2780],
        [0.7641, 0.6011, 0.2917],
        [0.3386, 0.2547, 0.9494]])


dtype = long, 0으로 초기화된 행렬


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
# touch.ones 해서 넣으면 모든 값을 1로 넣음
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


tensor(데이터의 행렬)값을 직접 주기

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


기존 tensor 바탕으로 새로운 tensor 생성
새로운 값을 제공받지 않는 한 입력 tensor의 속성 재사용


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* method 사이즈를 받음

print(x)

# 평균 0 정규 분포로부터 임의의 숫자로 채워만든 tensor
# 아레에 like(x, ~) 에 있는 x의 크기를 받아오기 위해 사용
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # 결과적으로 동일한 크기를 가짐

# 사이즈 출력
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.7239, -0.7691, -0.3634],
        [ 0.4168, -0.5937, -0.1780],
        [ 0.6938, -0.2897,  0.2882],
        [-0.9865, -0.9835, -1.1647],
        [-0.3904, -0.4180, -2.9102]])
torch.Size([5, 3])


torch.size() # 튜플 타입, 모든 튜플 연산 지원

## 연산

In [7]:
# 덧셈문법1
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.3910, -0.0771, -0.2365],
        [ 1.3655, -0.0396,  0.8213],
        [ 0.7856,  0.4156,  1.2339],
        [-0.8764, -0.1567, -0.6121],
        [ 0.4733,  0.2814, -2.2974]])


In [8]:
# 덧셈문법2
print(torch.add(x, y))

tensor([[-0.3910, -0.0771, -0.2365],
        [ 1.3655, -0.0396,  0.8213],
        [ 0.7856,  0.4156,  1.2339],
        [-0.8764, -0.1567, -0.6121],
        [ 0.4733,  0.2814, -2.2974]])


덧셈 : 결과 tensor를 인자로 제공

In [9]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.3910, -0.0771, -0.2365],
        [ 1.3655, -0.0396,  0.8213],
        [ 0.7856,  0.4156,  1.2339],
        [-0.8764, -0.1567, -0.6121],
        [ 0.4733,  0.2814, -2.2974]])


덧셈 : 바꿔치기(in-place) 방식



In [10]:
# y에 x더해서 y에 넣기
y.add_(x)
print(y)

tensor([[-0.3910, -0.0771, -0.2365],
        [ 1.3655, -0.0396,  0.8213],
        [ 0.7856,  0.4156,  1.2339],
        [-0.8764, -0.1567, -0.6121],
        [ 0.4733,  0.2814, -2.2974]])


바꿔치기(in-place) 방식으로 tensor의 값을 변경하는 연산 뒤에는 '_'가 붙는다


In [11]:
# numpy스러운 인덱싱 표기 방법 사용 가능
print(x[:, 1])

tensor([-0.7691, -0.5937, -0.2897, -0.9835, -0.4180])


크기 변경 : tensor의 크기나 모양을 변경하고 싶을 때 touch.view 사용

In [12]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # -1은 다른 차원에서 유추
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


tensor에 하나의 값만 존재한다면 ``.item()`` 사용 -> 숫자값 얻음

In [13]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.0470])
-1.0470397472381592


추가적인 Tensor 연산 확인하는 곳 :  
http://pytorch.org/docs/torch


## NumPy 변환(Bridge)
Torch Tensor를 numpy배열(array)로 변환 혹은 반대
Torch Tensor와 numpy배열은 메모리 공간을 공유 = 하나를 변경하면 다른 하나도 변경 됨

### Torch Tensor -> Numpy 배열 변환

In [16]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


numpy 배열값 변화 확인


In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Numpy 배열 -> Torch Tensor 변환
np 배열을 변경하면 torch tensor 값이 자동 변경되는 것 확인

In [18]:
import numpy as np
a = np.ones(5) # np로 정의
b = torch.from_numpy(a) # torch 화
np.add(a, 1, out=a) # 결과가 저장되는 위치. out=none 새로 할당된 배열 반환.
print(a) # 원래 1인데 위에서 np+1을 함
print(b) # np 결과값 따라 tensor에도 값이 더해짐

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CharTensor를 제외한  
CPU 상의 모든 Tensor는 NumPy로 변환 가능  
NumPy에서 Tensor로 반대 변환도 가능

## CUDA Tensors

In [19]:
# 이 코드는 CUDA가 사용 가능한 환경에서만 실행됨
# `torch.device`를 사용하여 tensor를 GPU 안팎으로 이동
if torch.cuda.is_available():
    device = torch.device("cuda")          # CUDA device object(장치객체)로
    y = torch.ones_like(x, device=device)  # GPU에 직접적으로 tensor 생성하거나
    x = x.to(device)                       # .to("cuda") 사용
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # '.to'는 dtype도 함께 변경함

In [ ]:
출력
tensor([1.8994], device='cuda:0')
tensor([1.8994], dtype=torch.float64)